version: "2"
services:
  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: Dockerfiles/DockerfileJenkins
    ports:
      - 8080:8080
  registry:
    container_name: registry
    image: registry:2
    ports:
      - 5000:5000
    environment:
      # REGISTY_AUTH: htpasswd
      # REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      # REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
      REGISTRY_HTTP_TLS_KEY: /certs/domain.key
    volumes:
      - ./conf:/etc/docker/registry
      - ./data:/var/lib/registry
      - ./auth:/auth:ro
      - ./certs:/certs:ro
